# CMake generated Testfile for 
# Source directory: /mnt/c/Users/cisco/Desktop/dev/research/ziXn
# Build directory: /mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[abi_conformance_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/abi_conformance_test")
set_tests_properties([=[abi_conformance_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;112;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[zx_abi_smoke]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/zx_abi_smoke")
set_tests_properties([=[zx_abi_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;118;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[apic_basis_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/apic_basis_test")
set_tests_properties([=[apic_basis_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;123;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[apic_ref_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/apic_ref_test")
set_tests_properties([=[apic_ref_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;130;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[counters_smoke]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/counters_smoke")
set_tests_properties([=[counters_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;137;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[writeback_smoke]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/writeback_smoke")
set_tests_properties([=[writeback_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;144;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[constitutive_ref_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/constitutive_ref_test")
set_tests_properties([=[constitutive_ref_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;151;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[constitutive_plastic_work_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/constitutive_plastic_work_test")
set_tests_properties([=[constitutive_plastic_work_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;158;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[mc_return_map_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/mc_return_map_test")
set_tests_properties([=[mc_return_map_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;165;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[validation_tests]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/validation_tests")
set_tests_properties([=[validation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;172;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[norsand_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/norsand_test")
set_tests_properties([=[norsand_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;179;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[heave_validation_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/heave_validation_test")
set_tests_properties([=[heave_validation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;186;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[anisotropic_contact_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/anisotropic_contact_test")
set_tests_properties([=[anisotropic_contact_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;193;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[wheel_heave_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/wheel_heave_test")
set_tests_properties([=[wheel_heave_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;200;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[foot_heave_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/foot_heave_test")
set_tests_properties([=[foot_heave_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;207;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[anisotropy_scene_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/anisotropy_scene_test")
set_tests_properties([=[anisotropy_scene_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;214;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[presets_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/presets_test")
set_tests_properties([=[presets_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;221;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[authoring_map_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/authoring_map_test")
set_tests_properties([=[authoring_map_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;228;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[lod_filters_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/lod_filters_test")
set_tests_properties([=[lod_filters_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;235;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[lod_alignment_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/lod_alignment_test")
set_tests_properties([=[lod_alignment_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;242;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[lod_crack_free_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/lod_crack_free_test")
set_tests_properties([=[lod_crack_free_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;249;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[lod_mip_random_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/lod_mip_random_test")
set_tests_properties([=[lod_mip_random_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;256;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[lod_mip_chain_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/lod_mip_chain_test")
set_tests_properties([=[lod_mip_chain_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;263;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[mixture_assembly_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/mixture_assembly_test")
set_tests_properties([=[mixture_assembly_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;270;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[bog_memory_knob_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/bog_memory_knob_test")
set_tests_properties([=[bog_memory_knob_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;277;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[pcg_smoke_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/pcg_smoke_test")
set_tests_properties([=[pcg_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;284;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[mg_pcg_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/mg_pcg_test")
set_tests_properties([=[mg_pcg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;291;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[mg_prec_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/mg_prec_test")
set_tests_properties([=[mg_prec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;298;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[dambreak_integration_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/dambreak_integration_test")
set_tests_properties([=[dambreak_integration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;305;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[bogging_puddle_integration_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/bogging_puddle_integration_test")
set_tests_properties([=[bogging_puddle_integration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;312;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[lod_fallback_threshold_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/lod_fallback_threshold_test")
set_tests_properties([=[lod_fallback_threshold_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;319;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[lod_fallback_blend_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/lod_fallback_blend_test")
set_tests_properties([=[lod_fallback_blend_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;326;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[lod_fallback_sweep_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/lod_fallback_sweep_test")
set_tests_properties([=[lod_fallback_sweep_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;333;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[determinism_tests]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/determinism_tests")
set_tests_properties([=[determinism_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;340;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[determinism_strict_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/determinism_strict_test")
set_tests_properties([=[determinism_strict_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;347;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[determinism_script]=] "bash" "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/scripts/wsl-determinism.sh" "--scene" "dambreak" "--seed" "42" "--fallback" "off")
set_tests_properties([=[determinism_script]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;350;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[checksum_parity_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/checksum_parity_test")
set_tests_properties([=[checksum_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;358;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[determinism_ordering_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/determinism_ordering_test")
set_tests_properties([=[determinism_ordering_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;365;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[residency_hysteresis_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/residency_hysteresis_test")
set_tests_properties([=[residency_hysteresis_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;372;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[residency_prefetch_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/residency_prefetch_test")
set_tests_properties([=[residency_prefetch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;379;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[hbp_mu_eff_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/hbp_mu_eff_test")
set_tests_properties([=[hbp_mu_eff_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;386;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[hbp_viscous_update_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/hbp_viscous_update_test")
set_tests_properties([=[hbp_viscous_update_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;393;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[hbp_clamp_policy_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/hbp_clamp_policy_test")
set_tests_properties([=[hbp_clamp_policy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;400;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[hbp_stability_bound_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/hbp_stability_bound_test")
set_tests_properties([=[hbp_stability_bound_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;407;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[telemetry_schema_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/telemetry_schema_test")
set_tests_properties([=[telemetry_schema_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;414;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
add_test([=[telemetry_depth_test]=] "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/wsl-build/telemetry_depth_test")
set_tests_properties([=[telemetry_depth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;421;add_test;/mnt/c/Users/cisco/Desktop/dev/research/ziXn/CMakeLists.txt;0;")
